export type NormalBoxEvents =
  //!| "@beforeSet"
  //!| "@seted"
  //!| "@beforeChange"
  | "@changed"
  | "@changed[tree]"
  //!| "@beforeAdd"
  //!| "@added"
  | "@normalize"
  | "@normalize[tree]"
  //!| "@beforeNormalize"
  //! | "@normalized"
  | "@listenerAdded"
  | "@listenerAdded[tree]"
  | "@listenerRemoved"
  | "@listenerRemoved[tree]";
